USE [C:\USERS\DEVIN\SOURCE\REPOS\STONEWOODBOOKS\STONEWOODBOOKS\APP_DATA\STONEWOODDATA.MDF];

CREATE TABLE [dbo].[AuthorPhone](
    [AID] int FOREIGN KEY REFERENCES Author(AID),
    [Phone] bigint NOT NULL,
    CONSTRAINT Pk_AuthorPhone PRIMARY KEY ([AID], [Phone]));


INSERT INTO AuthorPhone(AID, Phone)
VALUES
	(1, 8072221919),
	(2, 4885550134),
	(3, 9663250208);