USE [C:\USERS\DEVIN\SOURCE\REPOS\STONEWOODBOOKS\STONEWOODBOOKS\APP_DATA\STONEWOODDATA.MDF];

CREATE TABLE [dbo].Books_Authored(
[ISBN] INT FOREIGN KEY REFERENCES Books([ISBN]),
[AID] INT FOREIGN KEY REFERENCES Author([AID])
CONSTRAINT PK_BooksAuthored PRIMARY KEY([ISBN], [AID]));


INSERT INTO Books_Authored(ISBN, AID)
VALUES
	(0446364193, 1),
	(0439064872, 2),
	(0684801221, 3);