USE [C:\USERS\DEVIN\SOURCE\REPOS\STONEWOODBOOKS\STONEWOODBOOKS\APP_DATA\STONEWOODDATA.MDF]

CREATE TABLE OrderItem(
[ItemNumber] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[ItemPrice] DECIMAL(18,2) NOT NULL,
[OrderID] INT FOREIGN KEY REFERENCES Orders(OrderID),
[ISBN] INT FOREIGN KEY REFERENCES Books(ISBN),
[Username] VARCHAR(12) FOREIGN KEY REFERENCES Customer(Username));