USE [C:\USERS\DEVIN\SOURCE\REPOS\STONEWOODBOOKS\STONEWOODBOOKS\APP_DATA\STONEWOODDATA.MDF]

CREATE TABLE Orders(
[OrderID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[OrderDate] DATE NOT NULL,
[OrderValue] DECIMAL(18,2) NOT NULL,
[Username] VARCHAR(12) FOREIGN KEY REFERENCES Customer(Username));