USE [C:\USERS\DEVIN\SOURCE\REPOS\STONEWOODBOOKS\STONEWOODBOOKS\APP_DATA\STONEWOODDATA.MDF];

CREATE TABLE [dbo].[SuppliedBy](
[ISBN] int FOREIGN KEY REFERENCES Books(ISBN),
[SupplierID] int FOREIGN KEY REFERENCES Supplier(SupplierID),
CONSTRAINT Fk_SuppliedBy PRIMARY KEY CLUSTERED([ISBN], [SupplierID]));

INSERT INTO SuppliedBy(ISBN, SupplierID)
VALUES
(0446364193, 4),
(0439064872, 2),
(0684801221, 1);